# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30ec81ce4ea1ca401e559afbe00ee157bb2697898587f06b0ec3a59562a3f44f8f1ae1a3aab189ef3b22913b57b30c0788fec66f69c6a864a19c53d2c56126ea

test:
  secret_key_base: 8622da76feb42b7a3465574bac35ac23101a0ef0b369c78e495f0d829adf745db3092f3e39f8cdb5fde27aedd8d4d1bd767bcc0d15e70251e831804da9a94e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
